<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class History extends Model
{
    protected $fillable = [
    	'people_id',
        'medical',
		'codigo', 
		'motive', 
		'current_illness' ,
		'personal_history',
		'mon_history', 
		'dad_history', 
		'sons_history', 
		'brot_history', 
		'gynecology', 
		'alcohol',    
		'cigarettes',  
		'cofe',   
		'tobacco',  
		'fever',    
		'head_dizziness',   
		'headache',   
		'blurry_vision',   
		'double_vision',   
		'tearing',   
		'bleeding_nose',   
		'nose_secretion',  
		'halitosis',
		'cavities',
		'edentula', 
		'neck_pain', 
		'breast_masses',
		'breast_pain',
		'breast_secretion',
		'pulse',
		'torax_pain',
		'torax_angst',
		'dyspnoa',
		'heart_pain',
		'tachycardias',
		'oppression',
		'difficulty_breathing',
		'breathing_pain',
		'cough',
		'expectoration',

		'abdomen_pain',
		'diarrhea',
		'hernias',
		'genitals_man',
		'genitals_woman',
		'genital_micturition',
		'genital_anatomy',
		'genital_secretion',
		'genital_burning',
		'genital_pain',
		'fissure_anus',
		'neck_pain',
		'pain_limbs',
		'extremity_fatigue', 
		'heaviness_tips',  
		'swelling_extremities',
		'neurological_pain', 
		'neurological_dizziness',
		'disorientated', 
		//EXAMEN FISICO
		'vital_signs', 
		'weight', 
		'size', 
		'imc', 
		'fc', 
		'fr', 
		'ta', 
		'ca', 
		'pulse_fisic', 
		'skin', 
		'head', 

		'symmetrical_mouth',
		'rshas',   
		'nostrils',   
		'mouth_asymmetry',   
		'symmetrical_neck',   
		'asymmetrical_neck',   
		'symmetrical_sinuses',   
		'pulses', 
		'asymmetric_thorax',   
		'symmetric_thorax',   
		'rs_cs',   
		'soplo',   
		'ritmo',   
		'rs',   
		'mv',   
		'globose',   
		'flat',   
		'soft',   
		'painful',   
		'male_genitals',   
		'female_genitals',   
		'anal_canal',   
		'asymmetric_tips',   
		'symmetrical tips',   
		'eutrophic',   
		'atrophied',   
		'varicose_veins',   
		'edema',   
		'vigil',   
		'oriented',   
		'muscular_strength',   
		'language',   
		'reflexes',   
		'diagnoses', 
		'plan', 
		'observations', 

    ];
    public function people()
    {
        return $this->belongsTo('App\People', 'people_id');
        
    }
}
